# Creation of splits
This notebook presents how the splits for the models and the dataset version are handlet inside the plankton classifier pipeline.

###  Challenges and requiremnts of the split creation

In order to ensure the reproducibility of old splits and to provide enough felxibility to try new split, a own modul was coded that could fulfill following points:

- Reproducibility of old splits
- Creation of new splits based on past data versions
- Consideration of an OOD data set
- Simple to implement extensions with own split methods


## Movtivation
The split overview was created with the ambition to keep informations and track of the used split and allow a simple and understandable reproduction. Simplifies it, when multiple people work on the same project independetnt over time.

The split overview contains: 
$$
\small
\begin{array}{c}
\textbf{Description of the split overview dataframe}\\
\newline
\begin{array}{|l|l|}
\hline
\textbf{Column name} & \textbf{Description} \\
\hline
\text{Dataset version} & \text{Version of the Dataset used for the split} \\
\text{Split strategy} & \text{Used split strategy} \\ 
\text{Filter strategy} & \text{Used filtersplit strategy} \\
\text{Combined split hash} & \text{Hash value to identfiy the split} \\
\text{Description} & \text{Place to add a short description of the split} \\
\text{Args*} & \text{Arguments used inside the filter and split strategy are also saved}\\
\hline
\end{array}
\end{array}

$$




### Preparations

In [1]:
from pathlib import Path

# paths used in the notebook, 
# if you want to run the notebook on other data, please change the paths accordingly.
dataset_path = Path(r"..\data\mini_dataset")

print(f"Dataset path exists: {dataset_path.exists()}")

Dataset path exists: True

In [2]:
import pandas as pd

from lit_ecology_classifier.data_overview.overview_creator import OverviewCreator

artefacts_path = Path(r"..\data\mini_dataset_artifact")
overview_path = artefacts_path / "overview.csv"
if not artefacts_path.exists():
    artefacts_path.mkdir(parents=True)
    dataset_version = {"mini": dataset_path}
    overview_creator = OverviewCreator(dataset_version)
    overview_df = overview_creator.get_overview_df()

else:

    overview_df = pd.read_csv(overview_path)

## 1. Creation of a simple split

The simpelst way to create a split is to use the build in split strategies based on the `sklearn` library. The built in split strategies are:

- `Stratified`: Creates a stratified split based on the "class" column of the given dataset overview.
- `Random`: Creates a random split based on the given dataset overview.

and the filter strategies:

- `PlanktonFilter`: Allows the user to filter the dataset based on the version and if the OOD dataset should be included.

In [3]:
from lit_ecology_classifier.splitting.split_processor import SplitProcessor

split_processor = SplitProcessor(
                                artefacts_folder= artefacts_path,
                                image_overview= overview_df,
                                split_strategy= "Random",
                                filter_strategy= "PlanktonFilter"
                                )

random_split_df = split_processor.get_split_df()
random_split_df.head()

INFO:lit_ecology_classifier.splitting.split_processor:Arguments do not match, creating a new split.
INFO:lit_ecology_classifier.splitting.split_processor:Creating a new split based on the given split and filter strategy.
INFO:lit_ecology_classifier.splitting.split_processor:No class map provided, generating class map.
INFO:root:Classes to keep based on defined priority classes, if emtpy no prio are set:[]
             Classes to keep based on defined rest classes. If empty, no class are filtered out: []
INFO:lit_ecology_classifier.splitting.split_processor:Class map generated: {'aphanizomenon': 0, 'dinobryon': 1, 'keratella_quadrata': 2, 'polyarthra': 3, 'unknown': 4}
INFO:lit_ecology_classifier.splitting.split_processor:Df columns: Index(['image', 'class', 'sha256', 'date', 'version_mini_dataset'], dtype='object')

,image,class,sha256,date,version_mini_dataset,class_map,split
0,SPC-EAWAG-0P5X-1570543372901157-3725350526242-...,aphanizomenon,6fb0b3fa4b36614703ee1abdcf8efba4cd936982ca5fb6...,2019-10-08 14:02:52+00:00,True,0,train
1,SPC-EAWAG-0P5X-1570543374882008-3725352526408-...,aphanizomenon,09e4aa12fdc992bbd840b7913f6f35394637bc2135c49f...,2019-10-08 14:02:54+00:00,True,0,test
2,SPC-EAWAG-0P5X-1589472012505862-10217420880920...,aphanizomenon,1ace5cdd5a68e8cd5fa703c92ac7c6e6b1d362b517132f...,2020-05-14 16:00:12+00:00,True,0,train
3,SPC-EAWAG-0P5X-1589472120505648-10217528889899...,aphanizomenon,f9a38d8538b1ac64383199851c61ad2f7f784e430086ea...,2020-05-14 16:02:00+00:00,True,0,train
4,SPC-EAWAG-0P5X-1589472215513831-10217623897796...,aphanizomenon,9cfb8f3f9d36cb50c32bedc72724092a7a01576ccb8529...,2020-05-14 16:03:35+00:00,True,0,test

In [4]:
split_processor.get_class_map()

{'aphanizomenon': 0,
 'dinobryon': 1,
 'keratella_quadrata': 2,
 'polyarthra': 3,
 'unknown': 4}

It also generates a split entry that is not yet in the overview df.

In [5]:
split_entry = split_processor.get_new_split_entry()
split_entry.head()

,split_strategy,filter_strategy,combined_split_hash,description,priority_classes,rest_classes
0,Random,PlanktonFilter,ea15dc911b89efb03435a87e27cb6e0bde336c0071a8c1...,None,,

In [6]:
split_processor.save_split("Random split of the mini dataset")

INFO:lit_ecology_classifier.splitting.split_processor:Saving split data to: ..\data\mini_dataset_artifact\splits\ea15dc911b89efb03435a87e.csv
INFO:lit_ecology_classifier.splitting.split_processor:Split data saved to: ..\data\mini_dataset_artifact\splits\ea15dc911b89efb03435a87e.csv
INFO:lit_ecology_classifier.splitting.split_processor:Split metadata appended saved to: ..\data\mini_dataset_artifact\split_overview.csv

## 2. Useage with own split strategie

It also suport the implementation of own split strategies. Zo develop an own split strategy, the user has to implement a class that inherits from the `BaseSplit` class. The `BaseSplit` class and needs to contain atleast the method `perform_split` that returns a dictionary with atleast the keys `train`, `test` and `validation`. Further return values as OOD or somilar can also be used.

In [7]:
from sklearn.model_selection import train_test_split
from lit_ecology_classifier.splitting.split_strategies import BaseSplitStrategy

class ExampleSplitProcessor(BaseSplitStrategy):

    def perform_split(self, df, y_col = "class_map"):
        X = df["image"]
        y = df[y_col]
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

        X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

        X_test, X_test2, y_test, y_test2 = train_test_split(X_test, y_test, test_size=0.5, random_state=42)



        return {
            "train": [X_train,y_train],
            "test": [X_test, y_test],
            "val": [X_val, y_val],
            "test2": [X_test2, y_test2]
        }

In [8]:
split2 = split_processor.search_splits(
                                split_strategy = ExampleSplitProcessor(),
                                filter_strategy = "PlanktonFilter"
                            )
split2.head()

INFO:lit_ecology_classifier.splitting.split_processor:No existing split found, creating a new split.
INFO:lit_ecology_classifier.splitting.split_processor:Creating a new split based on the given split and filter strategy.
INFO:root:Classes to keep based on defined priority classes, if emtpy no prio are set:[]
             Classes to keep based on defined rest classes. If empty, no class are filtered out: []
INFO:lit_ecology_classifier.splitting.split_processor:Class map generated: {'aphanizomenon': -1, 'dinobryon': 0, 'keratella_quadrata': 1, 'polyarthra': 2, 'unknown': 3}
INFO:lit_ecology_classifier.splitting.split_processor:Df columns: Index(['image', 'class', 'sha256', 'date', 'version_mini_dataset'], dtype='object')

,image,class,sha256,date,version_mini_dataset,class_map,split
0,SPC-EAWAG-0P5X-1570543372901157-3725350526242-...,aphanizomenon,6fb0b3fa4b36614703ee1abdcf8efba4cd936982ca5fb6...,2019-10-08 14:02:52+00:00,True,-1,train
1,SPC-EAWAG-0P5X-1570543374882008-3725352526408-...,aphanizomenon,09e4aa12fdc992bbd840b7913f6f35394637bc2135c49f...,2019-10-08 14:02:54+00:00,True,-1,train
2,SPC-EAWAG-0P5X-1589472012505862-10217420880920...,aphanizomenon,1ace5cdd5a68e8cd5fa703c92ac7c6e6b1d362b517132f...,2020-05-14 16:00:12+00:00,True,-1,train
3,SPC-EAWAG-0P5X-1589472120505648-10217528889899...,aphanizomenon,f9a38d8538b1ac64383199851c61ad2f7f784e430086ea...,2020-05-14 16:02:00+00:00,True,-1,train
4,SPC-EAWAG-0P5X-1589472215513831-10217623897796...,aphanizomenon,9cfb8f3f9d36cb50c32bedc72724092a7a01576ccb8529...,2020-05-14 16:03:35+00:00,True,-1,train

In [9]:
split2["split"].value_counts()

split
train    3192
test2    1331
test     1330
val       798
Name: count, dtype: int64

# Not neeeded for the course ? ----------------------------